### PR TITLE
Attempt at fixing claroline/Claroline build

### PR DESCRIPTION
**Pull request by stefk**
Still doesn't work. Maybe the dependency cache is hiding a bug in a new version of some package. I deleted the cache, we'll see if we hit the same problem here.

### CODE REVIEW

**Comment by purplefish32** [comment]
LGTM

**Comment by stefk** [comment]
@purplefish32, I'm trying to reproduce the build errors seen in claroline/Claroline, so it isn't good until it fails ;)

**Comment by stefk** [comment]
lol

**Comment by stefk** [comment]
Almost 100% sure #986 solves the build issues. I still can't reproduce the problem here though :(

**Pull request closed without merging**
