### PR TITLE
[CoreBundle] - Remove flash fallback from embed templates

### PR DESCRIPTION
**Pull request by pitrackster**
Remove flash fallback from resource embed templates to avoid heratic media autoplay.
Also removed the comment from ```plugin/video-player/Controller/VideoPlayerController.php
```

### CODE REVIEW

**Comment by ngodfraind** [comment]
LGTM

**Comment by stefk** [comment]
@ngodfraind, you should wait for build completion before approving. @pitrackster, I think there's a superfluous `use` statement, the build is likely to fail because of that.

**Comment by stefk** [comment]
https://travis-ci.org/claroline/Distribution/builds/123342339#L2202

**Comment by stefk** [comment]
LGTM

**Pull request merged**
