### PR TITLE
[CoreBundle] Fixed use imports in thumbnail creator

### PR DESCRIPTION
**Pull request by ptsavdar**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    |no
| Fixed tickets |

### CODE REVIEW

**Comment by Elorfin** [comment]
@ngodfraind has already fixed it by upgrading the SVG dep to the correct version.

**Comment by Elorfin** [comment]
see https://github.com/claroline/Distribution/pull/2878.

**Comment by ptsavdar** [comment]
@Elorfin yeap, you're right. I didn't see that. I was having some errors in my installation and thought that someone mistakenly changed it. In that case we need to remove that also: https://github.com/claroline/Claroline/blob/master/composer.json#L94

**Comment by Elorfin** [comment]
Good catch !
I will update the composer.json. Thanks.

**Comment by Elorfin** [comment]
https://github.com/claroline/Claroline/pull/1242

**Pull request closed without merging**
