### PR TITLE
[CoreBundle] event soft delete

### PR DESCRIPTION
**Pull request by ngodfraind**
$event isn't always defined so this is the monkey patch.

Maybe the $node->setActive() block should be in the `if ($node->getClass() !== 'Claroline\CoreBundle\Entity\Resource\ResourceShortcut') {`condition. I don't know.

### CODE REVIEW

**Comment by stefk** [comment]
There's something wrong in that code. If `$eventSoftDelete` is put outside the loop, its value when the node is a shortcut could depend on the value of the previous iteration, which is completety random. Maybe the shortcut logic should be fixed instead. Aren't you the one who wrote it?

**Comment by ngodfraind** [comment]
You're right it should be in the loop and now it's ok. The shortcut logic is still a bit weird imo.

**Comment by LaurentGruber** [comment]
LGTM

**Comment by stefk** [comment]
LGTM

**Pull request merged**
