### PR TITLE
[ExoBundle] Allow anonymous to pass an Exercise

### PR DESCRIPTION
**Pull request by Elorfin**
This is the first working version of the anonymous access (issue #74).

As discussed in meeting, this implementation is not perfect but it works almost the same way the PHP did.

The problems of the current implementation are : 
- If the User refreshes the page, a new Paper is generated (it's IMHO the biggest problem).
- If the User changes the paper ID in the URL, he can access papers of other anonymous (but not the ones of authenticated Users)
- The User can only see his results at the end of the Exercise. He will not be able to get them if he quit the correction page.
- Some features of the Exercise can not work (e.g. max attempts).

This problems need to be fixed for the 16.09 release, so I don't close the related issue.

Is that OK for you @claroline/icap-ec ? Is there a feature you miss in the implementation ?

### CODE REVIEW

**Comment by stefk** [comment]
Why are you removing all these tests? AFAIK only one of them is concerned by your changes.

**Comment by Elorfin** [comment]
I have removed the corresponding entry point in the api because they are not used anymore. So the tests are obsoletes. It's just code cleaning and it's not directly related to the feature.

**Comment by stefk** [comment]
Most of the tested scenarios are still valid:

- submit an answer
- submit an answer in an invalid format
- submit an answer after the deadline
- submit an answer in another user paper

Those tests can't be obsolete. The features have problably been moved and tests and old code were left behind... It deserves a proper issue IMO.

**Comment by Elorfin** [comment]
Yes. The tests for the new methods have not been added. I will add them in this PR

**Comment by stefk** [comment]
LGTM

**Comment by kitan1982** [comment]
LGTM

**Comment by stefk** [comment]
LGTM

**Pull request merged**
