### PR TITLE
Scorm export for base resource types

### PR DESCRIPTION
**Pull request by Elorfin**
This PR implements SCORM export for the following resources : 
- Text
- File
  * PDF
  * Image
  * Audio / Video

### CODE REVIEW

**Comment by Elorfin** [comment]
**NB :** download for file resources has been disabled in the SCORM package.

**Comment by LaurentGruber** [comment]
LGTM

**Comment by kitan1982** [comment]
LGTM

**Comment by Elorfin** [comment]
LGTM

**Pull request merged**
