### PR TITLE
[CoreBundle] Adding some tests + test optimizations

### PR DESCRIPTION
**Pull request by ngodfraind**

### CODE REVIEW

**Comment by ngodfraind** [comment]
It runs in less than 2 minutes on travis now.

**Comment by stefk** [comment]
Yup. Added to #171, it will be a huge win: https://travis-ci.org/claroline/Distribution/builds/124174100#L2835. 1Go -> 200Mo in memory usage.

**Comment by stefk** [comment]
LGTM

**Comment by ngodfraind** [comment]
LGTM

**Pull request merged**
