### PR TITLE
upgrade doctrine dependencies to 2.5

### PR DESCRIPTION
**Pull request by Elorfin**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no

### CODE REVIEW

**Comment by stefk** [comment]
LGTM

**Comment by CPASimUSante** [comment]
I'm being overcautious, but how would you know this upgrade doesn't have BC breaks ?

**Comment by Elorfin** [comment]
@CPASimUSante : because this was the version we are already using. But for a reason, the last dependencies update has downgraded it to 2.4.

**Comment by Elorfin** [comment]
LGTM

**Pull request merged**
