### PR TITLE
Import dev tools

### PR DESCRIPTION
**Pull request by ngodfraind**

### CODE REVIEW

**Comment by ngodfraind** [comment]
@stefk 

You might want to update the [.travis](https://github.com/claroline/Distribution/blob/import-dev-tools/.travis.yml) for this PR.

**Comment by stefk** [comment]
Yup, I will do it tomorrow. LGTM

**Comment by stefk** [comment]
Wait you didn't add a .gitattributes?

**Comment by ngodfraind** [comment]
Not yet. True.

**Comment by ngodfraind** [comment]
Assuming I did it properly, it's ok now.

2016-04-11 17:41 GMT+02:00 Stéphane Klein <notifications@github.com>:

> Wait you didn't add a .gitattributes?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Distribution/pull/132#issuecomment-208408667>
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by stefk** [comment]
Looks good. If you want a quick way to test: 

    git archive -o latest.zip HEAD

**Comment by ngodfraind** [comment]
It worked.

2016-04-11 17:53 GMT+02:00 Stéphane Klein <notifications@github.com>:

> Looks good. If you want a quick way to test:
>
> git archive -o latest.zip HEAD
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Distribution/pull/132#issuecomment-208416437>
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by stefk** [comment]
On second thought, there's a big problem: the bundle won't be there in prod, but the kernel will still try to instantiate it because it's provided by composer.json#bundles. I see 2 solutions:

1. Move the bundle contents into the core and ignore each part with git attributes (Command/Dev, Resources/Dev, etc.).
2. Keep it as an independant bundle but available only in dev env (using [this method](https://github.com/claroline/Distribution/pull/132/files#diff-fda331673c7c455cf3e9ff5a67ce2297R11))

First option ensures no dev code is included in prod releases, second one avoids making the core codebase bigger. 

Actually there could be a third option, although a bit weird: using the second option *plus* ignoring everything in the bundle with git attributes except the bundle class. Result in prod would be an inactive and empty bundle.

**Comment by stefk** [comment]
@ngodfraind, if you're ok with it, I can commit third option + travis update on this branch.

**Comment by ngodfraind** [comment]
It's ok.

**Comment by ngodfraind** [comment]
I'm fine with that.

But I think we could just let it there aswell for prod (it's not really
worth all of that imo).

2016-04-12 9:32 GMT+02:00 Stéphane Klein <notifications@github.com>:

> @ngodfraind <https://github.com/ngodfraind>, if you're ok with it, I can
> commit third option + travis update on this branch.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Distribution/pull/132#issuecomment-208754888>
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by stefk** [comment]
@ngodfraind, it's really just one line of code + 3 git attributes. Good to merge IMO.

**Comment by ngodfraind** [comment]
LGTM

**Pull request merged**
