### PR TITLE
[ExoBundle] Add step name

### PR DESCRIPTION
**Pull request by eldoniel**
This PR adds a "name" field on the exercise's steps, as asked on the following issue: https://github.com/claroline/Distribution/issues/896

### CODE REVIEW

**Comment by Elorfin** [comment]
LGTM

**Comment by stefk** [comment]
*title* would have been better IMO.

**Comment by eldoniel** [comment]
Updated

**Comment by stefk** [comment]
LGTM

**Comment by Elorfin** [comment]
LGTM

**Pull request merged**
