### PR TITLE
[CoreBundle] Updating .gitattributes.

### PR DESCRIPTION
**Pull request by ngodfraind**
Related to #5 

Not sure it'll work and how to test it.
Also, I think it's possible to do a black magic one liner like ```*/**/Tests/*```. I just don't know the good one.

### CODE REVIEW

**Comment by ngodfraind** [comment]
This trick *should* work @stefk

**Comment by stefk** [comment]
You can test it with:
```
git archive --format=tar HEAD > test.tar.gz
```
(from the directory containing .gitattributes)

**Comment by ngodfraind** [comment]
It works !

**Comment by ngodfraind** [comment]
LGTM

**Comment by stefk** [comment]
LGTM

**Pull request merged**
