### PR TITLE
[CursusBundle] Cursus registration

### PR DESCRIPTION
**Pull request by ngodfraind**
This listener doesn't wait users are created to performs database queries (so if they're created in a batch, the query will crash).

Now we can force the session/cursus registration and we do it if the user has no id (there is no point querying anything in that case).

This change was suggested by @kitan1982 

We can also return null from the repositories if user->getId() is null (it may be better to do in the repository).

### CODE REVIEW

**Comment by ptsavdar** [comment]
LGTM

**Comment by kitan1982** [comment]
LGTM

**Comment by ngodfraind** [comment]
I should remove the UserManager from the constructor. It's not needed anymore.

**Comment by LaurentGruber** [comment]
LGTM

**Comment by ngodfraind** [comment]
LGTM

**Pull request merged**
