### PR TITLE
CLI tools improvements

### PR DESCRIPTION
**Pull request by ngodfraind**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no

- User removal command
- Workspace removal command
- files directory cleaning command

- some fixes/improvements for users/workspace csv import (no bc break).

### CODE REVIEW

**Comment by ngodfraind** [comment]
It's not completely over yet.

**Comment by LaurentGruber** [comment]
LGTM

**Comment by kitan1982** [comment]
LGTM

**Comment by LaurentGruber** [comment]
LGTM

**Pull request merged**
