### PR TITLE
Import formula plugin

### PR DESCRIPTION
**Pull request by ngodfraind**
Import FormulaPluginBundle

### CODE REVIEW

**Comment by LaurentGruber** [comment]
LGTM

**Comment by stefk** [comment]
Shouldn't mathjax be fetched with bower?

**Comment by ngodfraind** [comment]
Probably (https://github.com/claroline/Distribution/blob/import-with-history/plugin/formula/README.md)

**Comment by ngodfraind** [comment]
I installed locally from an update and it worked. This is great. Some bugfixes concerning the install are on the disable-plugin branch tho (but it's nothing more than toying with the bundles.bup.ini file).

**Comment by ngodfraind** [comment]
I'll add it in the root readme file.

**Comment by stefk** [comment]
@ngodfraind, @ptsavdar, it could be a good idea to test it with bower now, if we can avoid adding +1000 superfluous files to the repo history.

**Comment by ngodfraind** [comment]
I don't get how it works.

You can install it with `bower install MathJax`

**Comment by stefk** [comment]
I think I got it. This [listener](https://github.com/iCAPLyon1/FormulaPluginBundle/blob/master/Listener/FormulaPluginListener.php#L30) injects this [script](https://github.com/iCAPLyon1/FormulaPluginBundle/blob/master/Resources/views/Formula/plugin.js.html.twig), which includes this [file](https://github.com/iCAPLyon1/FormulaPluginBundle/blob/master/Resources/public/tinymce/plugins/formula/index.html) in a iframe. So maybe using the bower path for MathJax in the last one could be enough?

**Comment by ngodfraind** [comment]
I could not find the last file in the package/MathJax/... directories. That
was my problem.

2016-04-11 15:07 GMT+02:00 Stéphane Klein <notifications@github.com>:

> I think I got it. This listener
> <https://github.com/iCAPLyon1/FormulaPluginBundle/blob/master/Listener/FormulaPluginListener.php#L30>
> injects this script
> <https://github.com/iCAPLyon1/FormulaPluginBundle/blob/master/Resources/views/Formula/plugin.js.html.twig>,
> which includes this file
> <https://github.com/iCAPLyon1/FormulaPluginBundle/blob/master/Resources/public/tinymce/plugins/formula/index.html>
> in a iframe. So maybe using the bower path for MathJax in the last one
> could be enough?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Distribution/pull/127#issuecomment-208331558>
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by LaurentGruber** [comment]
What do we do ?

**Comment by stefk** [comment]
I guess at least we should wait for @ptsavdar's input. But merging this as is would be an error IMO.

**Comment by stefk** [comment]
Needs an entry in composer.json#replace (see #137).

**Comment by LaurentGruber** [comment]
Panos travail dessus

**Comment by ngodfraind** [comment]
LGTM

**Comment by ptsavdar** [comment]
LGTM

**Comment by ngodfraind** [comment]
LGTM

**Pull request merged**
