### PR TITLE
[CoreBundle] Cli imports

### PR DESCRIPTION
**Pull request by ngodfraind**

### CODE REVIEW

**Comment by stefk** [comment]
Same remark than for #645. What's the point of including new features in a bugfix release?

**Comment by ngodfraind** [comment]
@LaurentGruber told me to do this for the end of the week. I'm just assuming it's going to be on the 7.x.

These are only CLI tools but yeah, they're not bugfixes.

**Comment by LaurentGruber** [comment]
LGTM

**Comment by purplefish32** [comment]
This should not be merged into the 7.x, its a feature not a bugfix

**Pull request closed without merging**
