### PR TITLE
[CoreBundle] The user limit for role_user is checked with csv import.

### PR DESCRIPTION
**Pull request by ngodfraind**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Fixed tickets | #1302

### CODE REVIEW

**Comment by ngodfraind** [comment]
The other roles are already checked in the controller, so it allows to validate the user count with the CLI.

**Comment by LaurentGruber** [comment]
LGTM

**Comment by kitan1982** [comment]
LGTM

**Comment by LaurentGruber** [comment]
LGTM

**Pull request merged**
