### PR TITLE
[CoreBundle] Adds some indexes

### PR DESCRIPTION
**Pull request by ngodfraind**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Fixed tickets | #1318

Adds some indexes that looks relevant.

### CODE REVIEW

**Comment by stefk** [comment]
An index on claro_resource_rights(mask) should also be added: https://github.com/claroline/Distribution/issues/1176#issuecomment-251911387.

**Comment by LaurentGruber** [comment]
LGTM

**Comment by ngodfraind** [comment]
@stefk This solves most of #1176 issues coming from indexes.

**Comment by stefk** [comment]
LGTM

**Pull request merged**
