### PR TITLE
Add linter pass + phpmd rule in .travis

### LINKED ISSUE #286: [PHPMD] Remove unused local variables
Rule: *unusedcode.xml/UnusedLocalVariable*

### PR DESCRIPTION
**Pull request by stefk**
Follows claroline/Claroline#892. Fixes #286 and #693.

- enable PHPMD rule disallowing unused local variables or private fields
- add new MD linter tool to reject problematic stuff often seen in PRs, like loose comparisons, commented code, etc. (complete list [here](http://github.com/stefk/md/issues/1))

cc @claroline/commiters

### CODE REVIEW

**Comment by stefk** [comment]
PHPMD failure output: https://travis-ci.org/claroline/Distribution/builds/140474637#L2195
MD failure output: https://travis-ci.org/claroline/Distribution/builds/140474637#L2201

**Comment by stefk** [comment]
Good to merge.

**Comment by LaurentGruber** [comment]
LGTM

**Comment by Elorfin** [comment]
LGTM

**Pull request merged**
