### PR TITLE
[ChatBundle] Remove php file from js folder

### PR DESCRIPTION
**Pull request by stefk**
Should fix build errors of claroline/Claroline (e.g. https://travis-ci.org/claroline/Claroline/builds/153441047#L4127). Closes #980.

### CODE REVIEW

**Comment by ngodfraind** [comment]
can you disable phpmd for that pr (or force the merge) ?

**Comment by stefk** [comment]
I'd rather fix (again) the problematic [line](https://travis-ci.org/claroline/Distribution/builds/155280393#L188) in travis config.

**Comment by stefk** [comment]
Done (change detection is ok, we just have to avoid running static analysis tools when there's no modified/added files).

**Comment by LaurentGruber** [comment]
LGTM

**Comment by stefk** [comment]
LGTM

**Pull request merged**
