### PR TITLE
q&d patch for condition update

### PR DESCRIPTION
**Pull request by ngodfraind**
I don't think it should be merged, but I had to do this on a production instance to make it work.

Fatal error: arg 2 passed to StepConditionManager::edit() must be an instance of StepCondition, null given.
Called in StepManager line 140.

### CODE REVIEW

**Comment by stefk** [comment]
ping @claroline/innova

**Comment by Elorfin** [comment]
LGTM.

For issue about Path conditions, I think we have to ping @stmolivier too.

**Comment by LaurentGruber** [comment]
LGTM

**Comment by ngodfraind** [comment]
LGTM

**Pull request merged**
