### PR TITLE
[WebsiteBundle] Import

### PR DESCRIPTION
**Pull request by ngodfraind**

### CODE REVIEW

**Comment by ngodfraind** [comment]
Tested locally.

It works. The test suite is fired. It looks good. It can be merged.

**Comment by stefk** [comment]
Looks good, but there are extra migration files.

**Comment by ngodfraind** [comment]
Also there is a fix to do for the upload root dir (it's wrong after the merge because directories changed).

**Comment by ngodfraind** [comment]
@stefk 

Can you look at the travis log ? It's a weird php-cs error.

**Comment by stefk** [comment]
I think I got that one with the exo bundle. Problem is phpcs-fixer is applied to every file, and this PR includes images... I've added a fix in #156. I'm gonna make a separate PR for it.

**Comment by stefk** [comment]
@ngodfraind, probably fixed with #177.

**Comment by ngodfraind** [comment]
LGTM

**Comment by stefk** [comment]
LGTM

**Pull request merged**
