### PR TITLE
[FlashCardBundle] Fix err 500 caused by bad migration

### PR DESCRIPTION
**Pull request by remytms**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no

This PR comes to fix errors found by @CPASimUSante on the 8.x.
- Error 500 on page `create_note` and `list_notes`
- JS error on page `list_notes`

This PR replace the bad PR #1509.

### CODE REVIEW

**Comment by LaurentGruber** [comment]
LGTM

**Comment by purplefish32** [comment]
LGTM

**Comment by ngodfraind** [comment]
@LaurentGruber 
@purplefish32 
@remytms 
@stefk 

Shouldn't this be merged on the 8.x aswell ?

**Comment by LaurentGruber** [comment]
yes the pr : https://github.com/claroline/Distribution/pull/1521

**Pull request merged**
