### PR TITLE
[CoreBundle] Fixing model directory copy.

### PR DESCRIPTION
**Pull request by ngodfraind**
The copy is already handled by the resource manager copy method (wich handles recursion).
This code only duplicate every resource when it runs properly.

### CODE REVIEW

**Comment by ngodfraind** [comment]
It should fix #174

**Comment by ngodfraind** [comment]
@stefk 

Can you explain the Scrutinizer thing ?

**Comment by stefk** [comment]
I've just made a test build with scrutinizer. It's disabled now.

**Comment by ngodfraind** [comment]
LGTM

**Comment by stefk** [comment]
LGTM

**Pull request merged**
