### PR TITLE
[CoreBundle] API Security

### LINKED ISSUE #381: PDF viewer access with not connected/Anonymous users
Even if the rights are set for anonymous/not connected people to access to a PDF directly from URL, the PDF viewer (and download button if checked) are inactives.

### PR DESCRIPTION
**Pull request by ngodfraind**
This PR update the API security listener. It will support
- OAUTH password authentication
- OAUTH client_credential authentication
- HTTP authentication
- Cookie authentication
- Anonymous authentication

Look at the tests to see how it works.

The regex has been changed from ^/api to /api/.
Some api methods now have their missing security checks

Fix #381 
It also should fix the test errors of #338 

Squash it before merge.

### CODE REVIEW

**Comment by ngodfraind** [comment]
@claroline/maintainers Done.

**Comment by stefk** [comment]
LGTM

**Comment by ngodfraind** [comment]
LGTM

**Comment by ngodfraind** [comment]
still LGTM

**Pull request merged**
