### PR TITLE
Upgrade angular to 1.5.x

### PR DESCRIPTION
**Pull request by stefk**
Needs UI tests. Link to docker instance will be provided ASAP.

### CODE REVIEW

**Comment by stefk** [comment]
Here's the link: http://pr-658-1466002261.travis-build.claroline.net/claroline/

There might be an issue related to the angular upgrade in http://pr-658-1466002261.travis-build.claroline.net/claroline/admin/open/user_management#/users.

**Comment by LaurentGruber** [comment]
I don't see te issue in user management, what's the problem ?

**Comment by stefk** [comment]
There are two js errors in the browser console. I didn't find any bug in the ui neither, but it can't be good, something may be broken somewhere...

**Comment by Elorfin** [comment]
@stefk : can you provide the JS errors please ?

**Comment by Elorfin** [comment]
Just requested them for history / simplicity.

I don't get the same second error with Firefox.

```
Error: $select.parserResult is undefined
[226]/</</<.link/<@http://pr-658-1466002261.travis-build.claroline.net/claroline/dist/claroline-distribution-main-core-user-management-a6fe081c27ef87edc567.js:3:11379
Og</<@http://pr-658-1466002261.travis-build.claroline.net/claroline/dist/commons-a6fe081c27ef87edc567.js:5:18478
uf/this.$get</m.prototype.$digest@http://pr-658-1466002261.travis-build.claroline.net/claroline/dist/commons-a6fe081c27ef87edc567.js:3:8874
uf/this.$get</m.prototype.$apply@http://pr-658-1466002261.travis-build.claroline.net/claroline/dist/commons-a6fe081c27ef87edc567.js:3:10488
Ac/c/<@http://pr-658-1466002261.travis-build.claroline.net/claroline/dist/commons-a6fe081c27ef87edc567.js:1:11130
h/<.invoke@http://pr-658-1466002261.travis-build.claroline.net/claroline/dist/commons-a6fe081c27ef87edc567.js:1:21578
Ac/c@http://pr-658-1466002261.travis-build.claroline.net/claroline/dist/commons-a6fe081c27ef87edc567.js:1:11051
Ac@http://pr-658-1466002261.travis-build.claroline.net/claroline/dist/commons-a6fe081c27ef87edc567.js:1:11347
fe@http://pr-658-1466002261.travis-build.claroline.net/claroline/dist/commons-a6fe081c27ef87edc567.js:1:10646
@http://pr-658-1466002261.travis-build.claroline.net/claroline/dist/commons-a6fe081c27ef87edc567.js:6:1018
n.Callbacks/i@http://pr-658-1466002261.travis-build.claroline.net/claroline/packages/jquery/dist/jquery.min.js:2:27060
n.Callbacks/j.fireWith@http://pr-658-1466002261.travis-build.claroline.net/claroline/packages/jquery/dist/jquery.min.js:2:27828
.ready@http://pr-658-1466002261.travis-build.claroline.net/claroline/packages/jquery/dist/jquery.min.js:2:29619
J@http://pr-658-1466002261.travis-build.claroline.net/claroline/packages/jquery/dist/jquery.min.js:2:29804
```

**Comment by stefk** [comment]
@LaurentGruber, @Elorfin, the search box is broken (no filters, wrong results). Seems related to ui.select.

**Comment by stefk** [comment]
https://github.com/angular-ui/ui-select/issues/1325

Fixed by upgrading ui-select (https://github.com/angular-ui/ui-select/pull/1430).

**Comment by stefk** [comment]
New link: http://pr-658-1466581835.travis-build.claroline.net/claroline

**Comment by stefk** [comment]
New link: http://pr-658-1467983596.travis-build.claroline.net/claroline

**Comment by stefk** [comment]
When an item containing a date is added to the portfolio, the following exception is thrown on server side:

> request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "" at /var/www/html/claroline/vendor/claroline/distribution/plugin/portfolio/Manager/WidgetsManager.php line 181 {"exception":"[object] (InvalidArgumentException(code: 0):  at /var/www/html/claroline/vendor/claroline/distribution/plugin/portfolio/Manager/WidgetsManager.php:181)"} []

**Comment by pitrackster** [comment]
It seems that the problem pointed by @stefk is related to the portfolio bundle itself not angular...
see https://github.com/claroline/Distribution/issues/874

**Comment by LaurentGruber** [comment]
LGTM Yahoooooooo

**Comment by Elorfin** [comment]
LGTM

**Pull request merged**
