### PR TITLE
[ResourceManager] fixes non standard style for unpublished resource 

### PR DESCRIPTION
**Pull request by Elorfin**
The property `filter` is not supported in many browser.
It has been replaced by `opacity: 0.4`.

The value can be discussed.

### CODE REVIEW

**Comment by stefk** [comment]
Personnaly after some testing I wouldn't go under 0.5 or even 0.6 (remember the resource name and the menu actions should stay readable even if the contrast is low).

**Comment by Elorfin** [comment]
The opacity only impact the icon. Not the name nor the menu.
Is the case in your instance ?

I can set it to a higher value.

**Comment by stefk** [comment]
Nevermind, I've just set it on the whole node. Anyway, 0.5 is still a best fit IMO for icons/thumbnails that have an already light background (yellow, light green, etc.).

**Comment by Elorfin** [comment]
@stefk : done.

**Comment by stefk** [comment]
LGTM

**Comment by Elorfin** [comment]
LGTM

**Comment by stefk** [comment]
LGTM

**Pull request merged**
