### PR TITLE
[Distribution] Temporary folder

### PR DESCRIPTION
**Pull request by ngodfraind**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Fixed tickets | #1065

### CODE REVIEW

**Comment by Elorfin** [comment]
It would be better to remove your merge commit and do a rebase instead if you want to keep your history.

**Comment by ngodfraind** [comment]
It's ok, we can override it.

**Comment by ngodfraind** [comment]
I'm using git hooks and... it doesn't format properly.
@stefk

**Comment by Elorfin** [comment]
I've add the same problem multiple time. In fact, the fix fails each time there is comment block before the `namespace` statement.

**Comment by LaurentGruber** [comment]
LGTM

**Comment by kitan1982** [comment]
LGTM

**Comment by LaurentGruber** [comment]
LGTM

**Pull request merged**
