### PR TITLE
Add ESLint check on ES6 files

### PR DESCRIPTION
**Pull request by stefk**
See #693. 

- the check will be applied to js files within *Resources/modules/** directories
- standard used is described in https://github.com/claroline/Distribution/issues/693#issuecomment-227124134 (I've added single quotes preference and unix-style line endings as per ESLint suggestion)

Note that this PR just adds the check, it doesn't fix any actual errors. Those will have to be fixed on each modified files prior to a PR submission. 

There're currently 8000+ infractions to the standard. Most of them are indent and semi-colons issues that can be fixed automatically by ESLint using the `--fix` option. The remaining ones are mainly:

- unknown globals (ESLint requires globals to be specified explicitely to prevent leakage)
- missing import statements
- unused variables
- variables defined more than once
- console statements

cc @claroline/commiters

### CODE REVIEW

**Comment by stefk** [comment]
Failure output example: https://travis-ci.org/claroline/Distribution/builds/139998021#L1753

**Comment by stefk** [comment]
Good to merge IMO.

**Comment by Elorfin** [comment]
LGTM

**Comment by stefk** [comment]
LGTM

**Pull request merged**
