### PR TITLE
Merge 7.x into master

### PR DESCRIPTION
**Pull request by stefk**
No big conflicts, no migration clashes apparently.

@Elorfin, @eldoniel, I'm unsure about a change that happened in the 7.x. Correction directives were renamed and this caused a conflict for match questions: `correctionMatch` vs `matchCorrection`. I don't know which one must be chosen.

### CODE REVIEW

**Comment by eldoniel** [comment]
I did the change. correctionMatch was used, but the right name of the directive being matchCorrection, the directive wasn't called (causing the correction for the match question to be systematicly empty).
So I guess the right one should be matchCorrection.

**Comment by Elorfin** [comment]
@stefk : I have commited the correct one (as said by @eldoniel, it is matchCorrection).

**Comment by stefk** [comment]
Thanks. Forgot to mention this is a no-squash PR.

**Comment by Elorfin** [comment]
It seems there is also a bug in Match Questions in exo (can not reproduce it on 7.x branch). But for now, I don't see why it doesn't work. It sould !

**Pull request merged**
