### PR TITLE
[CoreBundle] Iframe resize fix

### PR DESCRIPTION
**Pull request by kitan1982**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Fixed tickets | #1208 

See also #1267.
It prevents the infinite loop by stopping it when the height is higher than the screen height.
It also stops the script if there is no iframe to resize.

### CODE REVIEW

**Comment by purplefish32** [comment]
LGTM

**Comment by LaurentGruber** [comment]
for testing : http://pr-1370-1476172825.travis-build.claroline.net/claroline/

**Comment by ptsavdar** [comment]
LGTM

**Comment by LaurentGruber** [comment]
LGTM

**Pull request merged**
