### PR TITLE
add minimal correction flag

### PR DESCRIPTION
**Pull request by pitrackster**
Add minimal correction flag for correction display

### CODE REVIEW

**Comment by purplefish32** [comment]
LGTM

**Comment by purplefish32** [comment]
Oops, I did it again...

**Comment by LaurentGruber** [comment]
LGTM

**Comment by LaurentGruber** [comment]
LGTM

**Comment by kitan1982** [comment]
LGTM

**Comment by Elorfin** [comment]
LGTM

**Pull request merged**
