### PR TITLE
PHP 7.4 compatiblity

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Fixed issues | -

### CODE REVIEW

**Comment by Elorfin** [comment]
```
if [ "$DIFF" != '' ]; then $ROOT/vendor/bin/php-cs-fixer fix --dry-run --diff --config=main/dev/Resources/[secure]/php-cs.php; fi

PHP needs to be a minimum version of PHP 5.6.0 and maximum version of PHP 7.3.*.
```
https://travis-ci.org/github/claroline/Distribution/builds/728357097#L11907

Also it's a little bit risky to build against PHP 7.4 while still supporting the 7.2.

**Comment by LaurentGruber** [comment]
on est sur la 2.14 de cs-fixer à partir de la 2.15 au moins il supporte php 7.4 de ce que j'ai vu. On peut monter de version sans souci vous pensez ?

**Comment by chalasr** [comment]
Yes, je fais ca lundi

**Comment by chalasr** [comment]
https://github.com/claroline/Claroline/pull/1514

**Pull request merged**
