### PR TITLE
Remove duplicate entry in composer.json

### PR DESCRIPTION
**Pull request by stefk**
| Q             | A
| ------------- | ---
| Bug fix?      | Not sure...
| New feature?  | no
| BC breaks?    | no

If we're lucky this might have something to do with broken builds.

### CODE REVIEW

**Comment by ngodfraind** [comment]
LGTM

**Comment by ngodfraind** [comment]
@stefk You need to amend. The broken test is unrelated.

**Comment by purplefish32** [comment]
LGTM

**Comment by stefk** [comment]
LGTM

**Pull request merged**
