### PR TITLE
Add phpcs step in travis config

### PR DESCRIPTION
**Pull request by stefk**
Future PRs would be expected to adhere to the default coding standard of [PHP-CS-Fixer](http://cs.sensiolabs.org), i.e. Symfony conventions. Of course, developers could also use that tool prior to the PR submission (e.g. with an IDE integration or a pre-commit hook).

[ ~~This is a test, not mergable yet.~~ As suggested by @pitrackster, we could also do a pass on the entire codebase. This would avoid superfluous noise in subsequent code reviews]

@claroline/commiters

### CODE REVIEW

**Comment by purplefish32** [comment]
@stefk : You should generally not do a pass on the whole code base as it is usually more pain than what it is worth because it introduces lots of merge conflicts etc...

I adhere the idea that all new code contributions should stick to the phpcs-fixer standards though and recommend using the git hooks that we have previously discussed to check the code prior to generating a pull request and/of travis build which saves valuable build/check time.

**Comment by LaurentGruber** [comment]
LGTM

**Comment by LaurentGruber** [comment]
@claroline/maintainers it's ok ?

**Comment by stefk** [comment]
No. The build is failing. I'll ping you when it's done.

**Comment by stefk** [comment]
@claroline/commiters, the entire code base has been fixed in #142, but it won't happen again for reasons highlighted by @purplefish32. From now on, travis builds will fail on coding style errors ([example](https://travis-ci.org/claroline/Distribution/builds/123275019)). If you don't want to loose time, please configure your IDE ([doc](http://cs.sensiolabs.org/#helpers)) or better, install a pre-commit hook for php-cs (see https://github.com/claroline/git-hooks).

**Comment by stefk** [comment]
@claroline/maintainers, good to merge.

**Comment by ngodfraind** [comment]
LGTM

**Comment by stefk** [comment]
Edited: wrong failing example -> see https://travis-ci.org/claroline/Distribution/builds/123272765#L2197

**Pull request merged**
