### PR TITLE
Sensio insight fixes

### PR DESCRIPTION
**Pull request by ngodfraind**

### CODE REVIEW

**Comment by stefk** [comment]
Updated analysis: https://insight.sensiolabs.com/projects/3124a018-3488-48ea-b73e-24a96664c0bf/analyses/2

**Comment by stefk** [comment]
https://insight.sensiolabs.com/projects/3124a018-3488-48ea-b73e-24a96664c0bf/analyses/3

**Comment by Elorfin** [comment]
We can merge the first set of fixes for Sensio Insight errors.

@claroline/maintainers ?

**Comment by ngodfraind** [comment]
It's fine for me
LGTM

**Comment by LaurentGruber** [comment]
LGTM

**Pull request merged**
