### PR TITLE
[path-bundle] Added tinymce to path description

### PR DESCRIPTION
**Pull request by ptsavdar**

### CODE REVIEW

**Comment by Elorfin** [comment]
LGTM

Maybe we can put the `TinymceConfigService` and `trustAsHtml` filter in the CoreBundle.

- The config service will permit to always have the same config for all TinyMCE fields.
- We need to regularly redefine trustAsHtml (we have the same filter in ExoBundle).

**Comment by ptsavdar** [comment]
@Elorfin You're right, me too I've thought that but then I considered that there are bundles and scripts in es6, compiled using webpack and others in es5 so I thought that maybe it would be better if we waited for a more homogenous version. For example I have these functions in WebsiteBundle but in es6. Which means it needs compiling, while in path bundle which doesn't use webpack we need the es5 version of it. Maybe I've thought it wrong, I don't know. What do you think? (But I totally agree with you @Elorfin in a certain point it would be nice if we grouped all these utilities in core bundle)

**Comment by stefk** [comment]
Shouldn't we merge this as is and open an issue to keep track of things we should move to the core (and discuss es5-6 issues)?

**Comment by ptsavdar** [comment]
Ok I'm merging it. LGTM

**Comment by LaurentGruber** [comment]
LGTM

**Comment by stefk** [comment]
17.46 min without cache (https://travis-ci.org/claroline/Distribution/builds/129978101)
6.38 with cache (https://travis-ci.org/claroline/Distribution/builds/129982238)
Win!

**Pull request merged**
