### PR TITLE
add matching css

### PR DESCRIPTION
**Pull request by charlotte42**
C'est surtout pour tester si on a fait la bonne procédure pour les branches et les PR.

### CODE REVIEW

**Comment by Elorfin** [comment]
LGTM

**Comment by stefk** [comment]
LGTM

**Comment by Elorfin** [comment]
@claroline/ujm : in fact the css files was not removed but was moved in Resources/public/less in order to integrate them in the main compiled less file.

No need to fix it for now, but just for you information.

**Comment by charlotte42** [comment]
Ok thanks

**Pull request merged**
