### PR TITLE
Fixing profile widget

### LINKED ISSUE #164: [SocialBundle] Warning in profile widget
In the profile widget on desktop 

Warning: Division by zero in /home/claco/vendor/claroline/core-bundle/Controller/ProfileController.php on line 232

### PR DESCRIPTION
**Pull request by ngodfraind**
Fixes #164 
Squash and merge.

### CODE REVIEW

**Comment by ngodfraind** [comment]
Do you need the fix on the v5 branch ?

**Comment by stefk** [comment]
Yes, bug fixes should be ported to v5 until the next stable release.

**Comment by ngodfraind** [comment]
LGTM

**Comment by ngodfraind** [comment]
This is not the first time I see this error. It's not related to this pr.

**Comment by stefk** [comment]
It might be related to [this change](https://github.com/claroline/ResultBundle/commit/e9999daae87dade50864812a082ab2de27a7c79e#diff-5da58026da138a568e2ac85ba227234cR42). The sorting order is supposed to be the opposite of the insertion order. But if the timestamps don't differ (i.e. rows were inserted in the same second), I guess sorting by time could be a problem.

Maybe we could do a sort by date desc *and* by node id.

**Comment by LaurentGruber** [comment]
LGTM

**Pull request merged**
