### PR TITLE
[ExoBundle] Exo v2 [Preview/WIP]

### PR DESCRIPTION
**Pull request by stefk**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes

### CODE REVIEW

**Comment by Elorfin** [comment]
@LaurentGruber @Pauooo : http://pr-1578-1481818420.travis-build.claroline.net/claroline/

**Comment by LaurentGruber** [comment]
new docker : http://pr-1578-1482237898.travis-build.claroline.net/claroline/

**Comment by Elorfin** [comment]
last docker : http://pr-1578-1482503640.travis-build.claroline.net/

**Comment by stefk** [comment]
last docker: http://pr-1578-1483581341.travis-build.claroline.net/

**Comment by Elorfin** [comment]
last docker : http://pr-1578-1483722929.travis-build.claroline.net/

**Comment by LaurentGruber** [comment]
New docker : http://pr-1578-1484234840.travis-build.claroline.net/claroline/

**Comment by LaurentGruber** [comment]
new docker : http://pr-1578-1485337890.travis-build.claroline.net/claroline/

**Comment by Pauooo** [comment]
New Docker : http://pr-1578-1485356646.travis-build.claroline.net/

**Comment by LaurentGruber** [comment]
new docker : http://pr-1578-1485534680.travis-build.claroline.net/claroline/

**Comment by LaurentGruber** [comment]
New docker : http://pr-1578-1485844237.travis-build.claroline.net/claroline/

**Comment by LaurentGruber** [comment]
New docker : pr-1578-1485868570.travis-build.claroline.net

**Pull request merged**
