### PR TITLE
[CursusBundle] hotAsset missing

### PR DESCRIPTION
**Pull request by ngodfraind**

### CODE REVIEW

**Comment by kitan1982** [comment]
LGTM

**Comment by Elorfin** [comment]
LGTM

**Comment by stefk** [comment]
It looks like a bugfix. Shouldn't it have gone in the 7.x branch first?

**Comment by ngodfraind** [comment]
yep

**Comment by stefk** [comment]
So, how do we do now? A separate PR on 7.x? ping @kitan1982

**Comment by kitan1982** [comment]
I think we will have to

**Comment by stefk** [comment]
@ngodfraind, the branch has been deleted here. Can you open a new PR?

**Comment by kitan1982** [comment]
I think this PR was based on the master.
I have already created a new branch from 7.x and made a PR.

**Comment by stefk** [comment]
Ok, thanks.

**Pull request merged**
