### PR TITLE
ReservationBundle into Dutch

### PR DESCRIPTION
**Pull request by om64**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any

### CODE REVIEW

**Comment by om64** [comment]
Don't waste your time validating this: I'm still working on it !

**Comment by LaurentGruber** [comment]
LGTM

**Comment by ngodfraind** [comment]
LGTM

**Comment by ngodfraind** [comment]
LGTM

**Pull request merged**
