### PR TITLE
directory import allowed

### PR DESCRIPTION
**Pull request by ngodfraind**
| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | yes/no
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any

Not over yet.

### CODE REVIEW

**Comment by ngodfraind** [comment]
Bon,

J'ai relancé mon import avec les données de Philippe (le premier était trop lent).
Il y a beaucoup et même en optimisant, ça reste lent.

Une série de question ne passe pas la validation, j'en ferai le retour ici après. Pour les reste, les imports s'effectuent convenablement. Je passerai dans certaines (lol) questions une fois qu'il aura terminé sur ma machine. Il y en a 1157 donc je ne vérifierai pas tout mais ça donnera une idée.
Si vous voulez qu'on le fasse sur un serveur pour vérifier que c'est correct on peu le faire aussi.

**Comment by ngodfraind** [comment]
Errors were found in the json schema for :/home/nico/Downloads/test/3541_Question 3.json
Errors were found in the json schema for :/home/nico/Downloads/test/1987_Question 2.json
Errors were found in the json schema for :/home/nico/Downloads/test/786_Question 2.json
Errors were found in the json schema for :/home/nico/Downloads/test/2437_TS-C6S5-APAN2-C-C1.json
Errors were found in the json schema for :/home/nico/Downloads/test/3166_TS-C4S6-ECS-P-C2.json
Errors were found in the json schema for :/home/nico/Downloads/test/4163_TS-C4S2-ECS-P-C2.json
Errors were found in the json schema for :/home/nico/Downloads/test/1236_Question 3.json
Errors were found in the json schema for :/home/nico/Downloads/test/3386_A..json
Errors were found in the json schema for :/home/nico/Downloads/test/2027_Question 2.json
Errors were found in the json schema for :/home/nico/Downloads/test/2416_TS-C3S7-ECS-C-C1.json
Errors were found in the json schema for :/home/nico/Downloads/test/2529_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/3332_Question 3.json
Errors were found in the json schema for :/home/nico/Downloads/test/2931_TS-C2S5-APAN1-F-B2.json
Errors were found in the json schema for :/home/nico/Downloads/test/4117_A..json
Errors were found in the json schema for :/home/nico/Downloads/test/2093_TS-C4S2-APAN1-C-B2.json
Errors were found in the json schema for :/home/nico/Downloads/test/4062_TS-C3S6-ECS-C-C2.json
Errors were found in the json schema for :/home/nico/Downloads/test/2205_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/2234_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/3339_Question 7.json
Errors were found in the json schema for :/home/nico/Downloads/test/185_Question 3d.json
Errors were found in the json schema for :/home/nico/Downloads/test/3327_Question 2.json
Errors were found in the json schema for :/home/nico/Downloads/test/3235_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/2420_TS-C5S4-APAN1-P-C1.json
Errors were found in the json schema for :/home/nico/Downloads/test/2900_Question 3.json
Errors were found in the json schema for :/home/nico/Downloads/test/2629_Question 2.json
Errors were found in the json schema for :/home/nico/Downloads/test/3293_Question 4.json
Errors were found in the json schema for :/home/nico/Downloads/test/2432_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/188_Question 4b2.json
Errors were found in the json schema for :/home/nico/Downloads/test/806_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/1579_TS-C2S1-APAN1-P-C1.json
Errors were found in the json schema for :/home/nico/Downloads/test/785_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/2445_TS-C6S5-ECS-P-C2.json
Errors were found in the json schema for :/home/nico/Downloads/test/1934_TS-C4S2-COCO1-P-A2.json
Errors were found in the json schema for :/home/nico/Downloads/test/3605_A..json
Errors were found in the json schema for :/home/nico/Downloads/test/495_TS-C3S10-COCO1-C-B1-1.json
Errors were found in the json schema for :/home/nico/Downloads/test/1235_Question 2.json
Errors were found in the json schema for :/home/nico/Downloads/test/4120_B.1.json
Errors were found in the json schema for :/home/nico/Downloads/test/1518_TS-C1S4-APAN1-P-B2.json
Errors were found in the json schema for :/home/nico/Downloads/test/2453_TS-C3S9-APAN1-C-B2.json
Errors were found in the json schema for :/home/nico/Downloads/test/2424_TS-C6S2-ECS-P-C2.json
Errors were found in the json schema for :/home/nico/Downloads/test/2408_TS-C1S4-ECS-C-C2.json
Errors were found in the json schema for :/home/nico/Downloads/test/3522_A..json
Errors were found in the json schema for :/home/nico/Downloads/test/3734_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/1234_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/5_TS-C1S1-COCO1-F-A2.json
Errors were found in the json schema for :/home/nico/Downloads/test/291_TS-C3S10-ECS-F-C1-1.json
Errors were found in the json schema for :/home/nico/Downloads/test/2769_TS-C6S4-ECS-C-C2.json
Errors were found in the json schema for :/home/nico/Downloads/test/211_Question 4b2.json
Errors were found in the json schema for :/home/nico/Downloads/test/3617_B..json
Errors were found in the json schema for :/home/nico/Downloads/test/3054_Question 4.json
Errors were found in the json schema for :/home/nico/Downloads/test/2404_TS-C1S4-ECS-F-C2.json
Errors were found in the json schema for :/home/nico/Downloads/test/230_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/1828_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/3648_TS-C3S4-APAN2-P-C1.json
Errors were found in the json schema for :/home/nico/Downloads/test/2428_TS-C6S4-ECS-F-C2.json
Errors were found in the json schema for :/home/nico/Downloads/test/2139_Question 2.json
Errors were found in the json schema for :/home/nico/Downloads/test/3060_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/2514_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/3370_B..json
Errors were found in the json schema for :/home/nico/Downloads/test/2223_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/2246_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/3286_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/3656_TS-C3S4-ECS-C-C2.json
Errors were found in the json schema for :/home/nico/Downloads/test/3751_C.2.json
Errors were found in the json schema for :/home/nico/Downloads/test/4155_TS-C4S5-ECS-C-C2.json
Errors were found in the json schema for :/home/nico/Downloads/test/2747_Question 4E.json
Errors were found in the json schema for :/home/nico/Downloads/test/3382_E..json
Errors were found in the json schema for :/home/nico/Downloads/test/4121_B.2.json
Errors were found in the json schema for :/home/nico/Downloads/test/3417_TS-C3S9-APAN1-P-B2.json
Errors were found in the json schema for :/home/nico/Downloads/test/3049_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/2131_Question 2.json
Errors were found in the json schema for :/home/nico/Downloads/test/2412_TS-C3S1-ECS-C-C1 .json
Errors were found in the json schema for :/home/nico/Downloads/test/3780_D..json
Errors were found in the json schema for :/home/nico/Downloads/test/3549_Question 2.json
Errors were found in the json schema for :/home/nico/Downloads/test/3204_TS-C1S3-APAN2-P-C2.json
Errors were found in the json schema for :/home/nico/Downloads/test/2045_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/3638_Question 3.json
Errors were found in the json schema for :/home/nico/Downloads/test/29_Test.json
Errors were found in the json schema for :/home/nico/Downloads/test/4159_TS-C5S6-APAN2-P-C1.json
Errors were found in the json schema for :/home/nico/Downloads/test/1028_Question 5.json
Errors were found in the json schema for :/home/nico/Downloads/test/2336_Question 2.json
Errors were found in the json schema for :/home/nico/Downloads/test/3379_Question 3.json
Errors were found in the json schema for :/home/nico/Downloads/test/2473_TS-C3S9-COCO2-P-B2.json
Errors were found in the json schema for :/home/nico/Downloads/test/3272_Question 3.json
Errors were found in the json schema for :/home/nico/Downloads/test/1141_Question 2.json
Errors were found in the json schema for :/home/nico/Downloads/test/2238_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/3110_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/3809_A..json
Errors were found in the json schema for :/home/nico/Downloads/test/1026_Question 3.json
Errors were found in the json schema for :/home/nico/Downloads/test/2340_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/3375_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/1038_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/242_TS-C3S10-APAN1-P-B2-1.json
Errors were found in the json schema for :/home/nico/Downloads/test/3377_Question 2.json
Errors were found in the json schema for :/home/nico/Downloads/test/2461_TS-C3S9-APAN2-F-C1.json
Errors were found in the json schema for :/home/nico/Downloads/test/43_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/3826_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/3717_C..json
Errors were found in the json schema for :/home/nico/Downloads/test/2477_TS-C3S9-ECS-P-C2.json
Errors were found in the json schema for :/home/nico/Downloads/test/2739_Question 3B.json
Errors were found in the json schema for :/home/nico/Downloads/test/3524_B..json
Errors were found in the json schema for :/home/nico/Downloads/test/3781_E..json
Errors were found in the json schema for :/home/nico/Downloads/test/3273_Question 4.json
Errors were found in the json schema for :/home/nico/Downloads/test/2176_TS-C5S6-APAN1-P-B2.json
Errors were found in the json schema for :/home/nico/Downloads/test/2101_TS-C4S2-COCO1-C-A2.json
Errors were found in the json schema for :/home/nico/Downloads/test/4133_Question 2.json
Errors were found in the json schema for :/home/nico/Downloads/test/2762_Question 2.json
Errors were found in the json schema for :/home/nico/Downloads/test/2295_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/1942_TS-C4S2-COCO2-P-B1.json
Errors were found in the json schema for :/home/nico/Downloads/test/3197_TS-C1S3-ECS-P-C2.json
Errors were found in the json schema for :/home/nico/Downloads/test/3022_TS-C4S3-ECS-C-B2.json
Errors were found in the json schema for :/home/nico/Downloads/test/3455_B..json
Errors were found in the json schema for :/home/nico/Downloads/test/1517_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/511_TS-C3-S10-COCO1-P-B2-1.json
Errors were found in the json schema for :/home/nico/Downloads/test/3283_Question 4.json
Errors were found in the json schema for :/home/nico/Downloads/test/208_Question 3d.json
Errors were found in the json schema for :/home/nico/Downloads/test/3421_TS-C3S9-APAN2-C-C1.json
Errors were found in the json schema for :/home/nico/Downloads/test/1257_Question 2.json
Errors were found in the json schema for :/home/nico/Downloads/test/1486_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/3551_Question 3.json
Errors were found in the json schema for :/home/nico/Downloads/test/2189_TS-C5S6-COCO1-P-A2.json
Errors were found in the json schema for :/home/nico/Downloads/test/2784_TS-C3S8-ECS-P-C2.json
Errors were found in the json schema for :/home/nico/Downloads/test/3076_Question 4.json
Errors were found in the json schema for :/home/nico/Downloads/test/4024_TS-C1S1-COCO2-P-B2.json
Errors were found in the json schema for :/home/nico/Downloads/test/1481_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/3045_Question 2.json
Errors were found in the json schema for :/home/nico/Downloads/test/2172_TS-C5S6-APAN1-F-B2.json
Errors were found in the json schema for :/home/nico/Downloads/test/2497_TS-C1S3-APAN2-F-B2.json
Errors were found in the json schema for :/home/nico/Downloads/test/2672_Question 2.json
Errors were found in the json schema for :/home/nico/Downloads/test/2136_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/3154_TS-C4S6-APAN2-C-C1.json
Errors were found in the json schema for :/home/nico/Downloads/test/2441_TS-C6S5-ECS-C-C2.json
Errors were found in the json schema for :/home/nico/Downloads/test/1916_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/1007_TS-C3-S10-C0C01-P-B2-1.json
Errors were found in the json schema for :/home/nico/Downloads/test/3932_TS-C6S3-COCO1-F-A2.json
Errors were found in the json schema for :/home/nico/Downloads/test/3744_C..json
Errors were found in the json schema for :/home/nico/Downloads/test/1463_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/2350_Question 1.json
Errors were found in the json schema for :/home/nico/Downloads/test/2771_Question 2.json
Errors were found in the json schema for :/home/nico/Downloads/test/2887_Question 2.json
Errors were found in the json schema for :/home/nico/Downloads/test/3251_Question 4.json
Errors were found in the json schema for :/home/nico/Downloads/test/4122_B.2.json
Errors were found in the json schema for :/home/nico/Downloads/test/3287_Question 2.json
Errors were found in the json schema for :/home/nico/Downloads/test/1027_Question 4.json
Errors were found in the json schema for :/home/nico/Downloads/test/3190_TS-C6S5-COCO2-P-A2.json
Errors were found in the json schema for :/home/nico/Downloads/test/301_TS-C3S10-COCO1-P-B2-1.json

**Comment by ngodfraind** [comment]
Tout s'importe à l'exception de la liste d'erreur au dessus

**Comment by clarophil** [comment]
Concernant le serveur lea, je préfère qu'on attende la version finale pour ne pas le polluer avec des tonnes de questions en double ou en triple

**Pull request merged**
