### PR TITLE
[CoreBundle] Resource Icons customization

### PR DESCRIPTION
**Pull request by ptsavdar**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Fixed tickets | 

Adds the possibility to create new icon packs for Resource Icons. In order to create new icons, an administrator needs to go to Administration -> Appearance -> Icon packs management. And then create and edit his new icon packs. He can then change the active/current icon pack.

### CODE REVIEW

**Comment by ptsavdar** [comment]
Here's the travis instance to test: http://pr-2059-1488277940.travis-build.claroline.net/claroline/

**Comment by ptsavdar** [comment]
To be combined with the PR here : https://github.com/claroline/Claroline/pull/1087

**Comment by LaurentGruber** [comment]
idéalement il faudrait mettre le dossier icon_sets dans files/ et faire un lien symbolique de web/icon_sets vers files/ Pour que l'ensemble des éléments que l'utilisateurs peut ajouter soit au même endroit. Ce qui facilitera les backup.
On a commencé à le faire pour d'autres choses, il faudra faire encore la même chose au moins pour web/themes et web/uploads ...

**Comment by ptsavdar** [comment]
New travis instance (updated with latest changes): http://pr-2059-1488392222.travis-build.claroline.net/claroline

**Comment by ptsavdar** [comment]
@om64 Olivier, here are the new translation keys that I've added (in order to make easier the translation task):

resource_icon_set
resource_icon_set_management
create_new_icon_set
resource_icon_set_info_text
filename
new_icon_set
cannot_delete_active_default_icon_set
remove_icon_set_confirm_message
remove_icon_set_icon_confirm_message
icon_set_created_successfully
icon_set_updated_successfully
icon_set_delete_success
icon_set_delete_error
icon_set_icon_update_success
icon_set_icon_update_error
icon_set_icon_delete_error
icon_set_icon_delete_success
resource_icon_set_illustrator_options
resource_icon_set_illustrator_help
icon_set_dir_not_writable

**Comment by om64** [comment]
@ptsavdar Are they already translated into English in the JSON file in CoreBundle ?

**Comment by ptsavdar** [comment]
@om64 Yes, they are translated both in English and French. I've tried to translate some of them in other languages too. I don't know if I got them all right though.

**Comment by om64** [comment]
@ptsavdar These new keys should appear in the CoreBundle on Weblate, but I don't see them. Have you created new JSON files I have to import first ?

**Comment by om64** [comment]
@stefk Some piece if advice for me ? What's the process with new strings to translate ? I can't merge locally because of conflicts.

**Comment by ptsavdar** [comment]
@om64 Now that the branch is merged with master I think you can find the translated keys inside platform.xx.json files in translations.

**Pull request merged**
