### PR TITLE
Soft delete flag for resource delete event.

### PR DESCRIPTION
**Pull request by ngodfraind**
Soft delete flag for resource.

How to use:
In the approriate listener:

$event->enableSoftDelete();

### CODE REVIEW

**Comment by stefk** [comment]
LGTM. @claroline/ujm, this is for you.

**Comment by charlotte42** [comment]
Thank you. It's ok now

**Comment by ngodfraind** [comment]
LGTM

**Comment by purplefish32** [comment]
I have not tested but LGTM

**Comment by purplefish32** [comment]
LGTM

**Pull request merged**
