### PR TITLE
[ExoBundle][Urgent] fixes management of deleted questions

### PR DESCRIPTION
**Pull request by Elorfin**
As reported by @claroline/ujm there is a bug in the last fix done to manage deleted questions.
I have not detected it due to my test data sorry for that :s.

Can we include it in the 7.0.0 ? Because it's a major bug.

### CODE REVIEW

**Comment by stefk** [comment]
LGTM

**Comment by ngodfraind** [comment]
LGTM

**Comment by ngodfraind** [comment]
@stefk can't merge

**Comment by Elorfin** [comment]
LGTM

**Comment by stefk** [comment]
LGTM

**Pull request merged**
