### PR TITLE
[CoreBundle] Removing administration desktop tool.

### LINKED ISSUE #187: [Administration tools] Labels in Desktop tools
in Administration / Desktop tools
changing labels seem visible anywhere, whether on old or new workspaces.

How to apply modifications? Or where should we see them?

### PR DESCRIPTION
**Pull request by ngodfraind**
Fix #187

The tool was borderline useless and was removed.

### CODE REVIEW

**Comment by ngodfraind** [comment]
LGTM

**Comment by stefk** [comment]
LGTM if #187 proposal is ok for everybody.

**Comment by LaurentGruber** [comment]
LGTM

**Comment by ngodfraind** [comment]
LGTM

**Pull request merged**
